"""The final report: evidence, then conclusions, then what to run next.

Written to be read by somebody who did not run the study, in the order they
need it — what was measured and under what protocol, what the numbers show,
what follows for the next experiment, and where each claim's evidence lives.
Every number is regenerable from ``analysis/*.csv``, and the report says so, so
a reader who disagrees can recompute rather than argue.

Two rules the generator keeps
─────────────────────────────
**No number without its uncertainty and its n.** A mean over folds and
replicates is printed with the spread and the count, never on its own; a table
whose cells came from one measurement says so.

**No conclusion the flags contradict.** :func:`_conclusions` reads the
critical and warning flags first and states the caveats *before* the
recommendation they qualify, rather than after it in small print. If the study
found no plateau, the report leads with that; if no method beat the random
null, it leads with that.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from spectralquadnet.bandstudy import analysis as bsanalysis
from spectralquadnet.bandstudy import figures as bsfigures
from spectralquadnet.bandstudy import neural as bsneural
from spectralquadnet.bandstudy.config import BandStudyConfig
from spectralquadnet.bandstudy.pipeline import load_inputs
from spectralquadnet.bandstudy.store import MANIFEST
from spectralquadnet.reporting.tables import markdown_table

_log = logging.getLogger("spectralquadnet.bandstudy.report")

SEVERITY_MARK = {"critical": "🔴", "warning": "🟠", "info": "🔵"}

#: The metric every table reports, taken from the analysis module so the report
#: and the decisions cannot end up describing different quantities.
METRIC = bsanalysis.METRIC


def _read(cfg: BandStudyConfig, name: str) -> pd.DataFrame:
    """One analysis table, read back without pandas' string-to-NaN coercion.

    ``keep_default_na=False`` with an explicit ``na_values=[""]`` matters here:
    the default sentinel list contains bare tokens like ``null``, ``NA`` and
    ``None``, which are perfectly good *values* in these tables — a method's
    family, a fallback reason, a free-text rationale — and silently reading them
    back as missing put ``NaN`` in the published method-comparison table where
    the word ``null_model`` belonged. Empty cells, which is what
    ``DataFrame.to_csv`` writes for a real NaN, still parse as NaN.
    """
    path = cfg.analysis_dir / f"{name}.csv"
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path, keep_default_na=False, na_values=[""])


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None or (isinstance(value, float) and not np.isfinite(value)):
        return "—"
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.{digits}f}"
    return str(value)


# ══════════════════════════════════════════════════════════════════════
#  Sections
# ══════════════════════════════════════════════════════════════════════


def _header(cfg: BandStudyConfig, manifest: dict[str, Any]) -> list[str]:
    stages = manifest.get("stages", {})
    ran = (
        ", ".join(
            f"{name} ({info.get('n_done', 0)} done / {info.get('n_failed', 0)} failed)"
            for name, info in stages.items()
        )
        or "none recorded"
    )
    return [
        "# Spectral dimensionality and band selection — study report\n",
        f"*Generated by `python -m spectralquadnet.bandstudy.cli report`. "
        f"Study fingerprint `{cfg.fingerprint()}`. Every number below is recomputable from "
        f"`{cfg.analysis_dir}/*.csv` without a GPU or the patch cube.*\n",
        f"**Stages recorded:** {ran}\n",
    ]


def _protocol(cfg: BandStudyConfig, splits: dict[str, Any]) -> list[str]:
    lines = [
        "## 1. What was measured, and under what protocol\n",
        "The question is three questions, and they have different answers:\n",
        "1. **How many bands does this task need?** A budget sweep from "
        f"k = {min(cfg.budgets)} to the full k = {max(cfg.budgets)}, so the curve extends past "
        "every candidate elbow by construction.",
        "2. **Which bands?** Selection frequency over folds, replicates and methods, in "
        "nanometres, with the redundancy of each set quantified.",
        f"3. **Which method?** {len(cfg.methods)} strategies including two nulls — evenly spaced "
        "bands, and random subsets.\n",
        "### Leakage discipline\n",
        "| Partition | What it is allowed to do | Enforced by |",
        "|---|---|---|",
        "| `train` | Fit the band selectors, and fit the proxy models | Selectors receive "
        "`FoldData.train` and nothing else |",
        "| `calib` | Decide the band budget and the method | The analysis module reads only "
        '`split == "calib"` records |',
        "| `val ∪ test` | Confirm an already-fixed choice, once | Reachable only via "
        "`FoldData.reveal_heldout()`, which logs every call |\n",
        f"Protocol: **{cfg.split_scheme}** (acquisition-disjoint), folds "
        f"{list(cfg.folds)}, `split_eval_frac={cfg.split_eval_frac}`, "
        f"`calib_frac={cfg.calib_frac}` — the same builder and the same parameters "
        "`configs/data/spa40_90class_pfix.yaml` gives the training runs.\n",
    ]
    folds = splits.get("folds", {})
    if folds:
        lines += [
            markdown_table(
                ["fold", "train (selection)", "calib (decisions)", "held-out (confirm only)"],
                [
                    [
                        f,
                        f"{info['sizes']['train']:,}",
                        f"{info['sizes']['calib']:,}",
                        f"{info['sizes']['heldout']:,}",
                    ]
                    for f, info in sorted(folds.items())
                ],
            )
        ]
        lines += _calib_caveat(folds)
    lines += [
        f"\nFeature representation: **{cfg.features}** — the foreground-masked mean spectrum"
        + (
            " concatenated with the per-band spatial standard deviation"
            if cfg.features == "mean_sd"
            else ""
        )
        + f". Proxy estimators: {', '.join(cfg.proxies)}. "
        f"Replicates per (fold, method): {cfg.replicates} "
        f"({cfg.replicate_frac:.0%} stratified subsamples), plus one canonical selection on the "
        "whole training split.\n",
        "### Pre-registered decision rules\n",
        f"- A curve **plateaus** at the smallest k within **{cfg.plateau_tol:.3f}** macro-F1 of "
        "its own peak, and the plateau is *demonstrable* only if the curve extends past it.",
        f"- A selection is **stable** at mean replicate Jaccard ≥ **{cfg.stability_floor:.2f}**.",
        f"- A method is **effective** only if it beats a random subset of the same size by "
        f"≥ **{cfg.null_margin:.3f}** macro-F1 somewhere.\n",
    ]
    return lines


def _calib_caveat(folds: dict[str, Any]) -> list[str]:
    """What `calib` is on *this* dataset, and what that costs the decisions.

    The most important sentence in the protocol section, and one that only the
    split report can supply. Under the grouped scheme a class's training pool is
    a **single** acquisition bundle — its other bundle is held out — so the calib
    carve-out has no second group to take and falls back to a patch-level split
    of that one tray. Calib is therefore held out from the *gradient* but not
    from the *acquisition*, which is exactly the C-1 structure at a smaller
    scale.

    That is acceptable for what calib is used for here — ranking budgets and
    methods against each other, where any per-tray offset is common to every
    arm — and it is not acceptable as an absolute number. Saying so is the
    difference between a caveat and a defect.
    """
    first: dict[str, Any] = next(iter(folds.values()), {})
    report = first.get("split_report", {})
    n_shared = len(report.get("classes_sharing_groups_calib", []) or [])
    n_classes = int(report.get("n_classes", 0) or 0)
    sizes = first.get("sizes", {})
    per_class = (sizes.get("calib", 0) / n_classes) if n_classes else 0.0

    lines = [
        f"\n`calib` holds ≈{per_class:.0f} patches per class. Two properties of it bound what "
        "the decisions below can mean:\n",
    ]
    if n_shared:
        lines.append(
            f"- **It is a patch-level carve-out of the training bundle** for {n_shared} of "
            f"{n_classes} classes. Under the grouped scheme a class's training pool is a single "
            "acquisition bundle — the other one is held out — so there is no second group for "
            "calib to take. Calib is held out from the *gradient* but not from the "
            "*acquisition*. Its absolute level is therefore optimistic relative to `val ∪ test`, "
            "and §7 measures by how much."
        )
    else:
        lines.append(
            f"- It is group-disjoint from train for all {n_classes} classes, so its level is "
            "directly comparable to the held-out split's."
        )
    lines.append(
        f"- At ≈{per_class:.0f} patches per class, macro-F1 on calib carries real sampling "
        "noise. The study therefore reads it **relatively** — budget against budget, method "
        "against method, all on the same rows — and never as an estimate of deployed "
        "performance. The replicate spread in `curves.csv` is the scale that noise is judged at."
    )
    lines.append("")
    return lines


def _budget_section(cfg: BandStudyConfig, curves: pd.DataFrame, trends: pd.DataFrame) -> list[str]:
    if curves.empty:
        return ["## 2. How many bands?\n", "*No proxy records — the sweep has not run.*\n"]

    lines = ["## 2. How many bands?\n"]
    shapes = trends["shape"].value_counts().to_dict() if not trends.empty else {}
    if shapes:
        lines.append(
            "Across every (fold × method × proxy) curve: "
            + ", ".join(f"**{v}** {k.replace('_', ' ')}" for k, v in shapes.items())
            + ".\n"
        )
        demonstrable = int(trends["plateau_demonstrable"].sum())
        lines.append(
            f"{demonstrable} of {len(trends)} plateaus are *demonstrable* — that is, the curve "
            "was recorded past the plateau. A plateau at the last evaluated budget is the "
            "endpoint of a truncated curve, which is the defect CHANGES M-14 identified in both "
            "of the repository's shipped selections.\n"
        )

    best = curves.groupby("budget")["score"].max()
    full = int(max(curves["budget"]))
    reference = float(best.get(full, np.nan))
    rows = []
    for k in sorted(best.index):
        score = float(best[k])
        rows.append(
            [
                k,
                _fmt(score),
                f"{score - reference:+.4f}" if np.isfinite(reference) else "—",
                (
                    f"{100.0 * score / reference:.1f}%"
                    if np.isfinite(reference) and reference > 0
                    else "—"
                ),
                f"{100.0 * (1 - k / full):.0f}%",
            ]
        )
    lines += [
        "### Best score achieved at each budget (any method, any proxy, calib)\n",
        markdown_table(
            ["k", "best macro-F1", "Δ vs full cube", "% of full-cube score", "band reduction"],
            rows,
        ),
        "\n*A maximum over methods, so it is an optimistic envelope and is shown as one — the "
        "per-method means in `analysis/curves.csv` are what a single choice would actually get.*\n",
    ]

    if not trends.empty:
        lines += [
            "\n### Where each estimator family stops improving\n",
            markdown_table(
                [
                    "proxy",
                    "median plateau k",
                    "median knee k",
                    "curves still rising at k_max",
                    "median headroom past plateau",
                ],
                [
                    [
                        proxy,
                        int(block["plateau_budget"].median()),
                        int(block["knee_budget"].median()),
                        f"{int((~block['plateau_demonstrable']).sum())} / {len(block)}",
                        f"{block['headroom_past_plateau'].median():+.4f}",
                    ]
                    for proxy, block in trends.groupby("proxy")
                ],
            ),
            "\nThe three proxies are a generative linear model, a discriminative linear model and "
            "a nonlinear ensemble. Where they agree, the budget is a property of the spectra; "
            "where they disagree, it is a property of the estimator — and the neural "
            "confirmation is the only thing that settles which applies to the deployed network.\n",
        ]
    return lines


def _method_section(
    cfg: BandStudyConfig, ranking: pd.DataFrame, margins: pd.DataFrame
) -> list[str]:
    if ranking.empty:
        return ["## 3. Which method?\n", "*No records.*\n"]
    lines = [
        "## 3. Which method?\n",
        "Ranked on mean calib macro-F1 at k ≤ 40, which is where selection methods can differ "
        "at all — by k = 128 every method holds most of the spectrum and the ranking is noise.\n",
        markdown_table(
            [
                "method",
                "family",
                "supervised",
                "mean F1 (k≤40)",
                "best F1",
                "at k",
                "best Δ vs random",
                "effective?",
                "stability (k≤40)",
                "select time",
            ],
            [
                [
                    r["method"],
                    r["family"],
                    "yes" if r["supervised"] else "no",
                    _fmt(r["mean_score_k_le_40"]),
                    _fmt(r["best_score"]),
                    int(r["best_budget"]),
                    (
                        f"{r['best_margin_vs_random']:+.4f}"
                        if np.isfinite(r["best_margin_vs_random"])
                        else "—"
                    ),
                    # `random` is the yardstick, so scoring it against itself is
                    # meaningless and printing "NO" there would read as a verdict.
                    (
                        "*(the null)*"
                        if r["method"] == "random"
                        else ("**yes**" if r["effective"] else "**NO**")
                    ),
                    _fmt(r["mean_jaccard_k_le_40"], 3),
                    f"{r['mean_selection_seconds']:.2f}s",
                ]
                for r in ranking.to_dict("records")
            ],
        ),
        "\n**`effective` is the study's pass/fail.** With neighbour correlations above 0.99, a "
        "random 20-band subset already spans most of the usable spectrum, so a method that does "
        "not beat one has been shown to subset rather than to select. `uniform` and `random` are "
        "the nulls and are in the table to be beaten.\n",
    ]
    if not margins.empty:
        # The full budget is excluded: there every method selects every band, so
        # the margin is identically zero by construction and reporting it as
        # "no method beat the null" would be an arithmetic identity dressed as a
        # finding.
        full = int(margins["budget"].max())
        by_budget = margins[margins["budget"] < full].groupby("budget")["margin"].max()
        crossing = [int(k) for k in by_budget.index if by_budget[k] < cfg.null_margin]
        if crossing:
            lines.append(
                f"At budgets {crossing}, **no** method beats the random null by "
                f"{cfg.null_margin:.3f}. Band identity carries no measurable advantage over band "
                "count there — only band count does.\n"
            )
    return lines


def _wavelength_section(
    cfg: BandStudyConfig, consensus: pd.DataFrame, inputs: Any, budget: int
) -> list[str]:
    if consensus.empty:
        return ["## 4. Which wavelengths?\n", "*No consensus table.*\n"]
    # The merge width is derived from the cube's own band spacing, not fixed.
    regions = bsanalysis.consensus_regions(consensus, inputs.wavelengths, threshold=0.5)
    spacing = float(np.median(np.diff(np.sort(np.asarray(inputs.wavelengths, dtype=float)))))
    top = consensus.head(15)
    lines = [
        "## 4. Which wavelengths?\n",
        f"Selection frequency at k = {budget}, over supervised methods × "
        f"{len(cfg.folds)} folds × {cfg.replicates + 1} selection scopes "
        f"({int(consensus['n_selections'].iloc[0])} selections in total). Unsupervised methods "
        "are excluded: they choose without reference to the label, so including them would "
        "dilute a claim about *discriminative* wavelengths with a claim about where bands are.\n",
        markdown_table(
            ["band", "λ (nm)", "chosen in"],
            [
                [
                    int(r["band"]),
                    f"{r['wavelength_nm']:.1f}",
                    f"{100 * r['selection_frequency']:.0f}% of selections",
                ]
                for r in top.to_dict("records")
            ],
        ),
    ]
    if regions:
        lines += [
            f"\n**Contiguous regions selected in ≥50% of selections** (bands within "
            f"{6 * spacing:.0f} nm merged — six of this cube's {spacing:.1f} nm steps, since "
            "adjacent bands are one spectral feature and not two):\n",
            markdown_table(
                ["region (nm)", "width (nm)", "bands"],
                [[f"{lo:.0f} – {hi:.0f}", f"{hi - lo:.0f}", n] for lo, hi, n in regions],
            ),
            "\n*These are the wavelengths a paper may name. Regions from a method flagged "
            "unstable in §6 are not — an unstable method's specific bands are an accident of the "
            "sample, however well the set scores.*\n",
        ]
    else:
        lines.append(
            "\n**No band is selected in even half of the selections.** The methods do not agree "
            "on which wavelengths matter, so no wavelength claim is supported by this study — "
            "which is consistent with a cube whose 256 bands carry far fewer than 256 degrees of "
            "freedom, and where many subsets are interchangeable.\n"
        )
    return lines


def _stability_section(
    cfg: BandStudyConfig,
    stability: pd.DataFrame,
    cross_fold: pd.DataFrame,
    redundancy: pd.DataFrame,
) -> list[str]:
    lines = ["## 5. Stability and redundancy\n"]
    if stability.empty:
        return lines + ["*Not computed.*\n"]

    small = stability[stability["budget"] <= 40]
    chance = small[small["method"] == "random"]["mean_jaccard"].mean()
    rows = []
    for method, block in small.groupby("method"):
        mean_j = float(block["mean_jaccard"].mean())
        cross = (
            float(
                cross_fold[(cross_fold["method"] == method) & (cross_fold["budget"] <= 40)][
                    "mean_jaccard"
                ].mean()
            )
            if not cross_fold.empty
            else float("nan")
        )
        red = redundancy[(redundancy["method"] == method) & (redundancy["budget"].between(10, 50))]
        rows.append(
            [
                method,
                _fmt(mean_j, 3),
                "yes" if np.isfinite(mean_j) and mean_j >= cfg.stability_floor else "**no**",
                _fmt(cross, 3),
                _fmt(red["rank_efficiency"].mean(), 3) if not red.empty else "—",
                _fmt(red["wavelength_coverage"].mean(), 2) if not red.empty else "—",
            ]
        )
    lines += [
        markdown_table(
            [
                "method",
                "replicate Jaccard (k≤40)",
                f"≥ {cfg.stability_floor:.2f}?",
                "cross-fold Jaccard",
                "rank efficiency (10≤k≤50)",
                "spectral coverage",
            ],
            rows,
        ),
        f"\nChance-level replicate agreement at k ≤ 40 is Jaccard ≈ **{_fmt(chance, 3)}** "
        "(the `random` row). Read every method against that, not against 0.\n",
        "**Cross-fold Jaccard** is the harder and more interesting number: the two folds hold "
        "out *different acquisition bundles*, so a band set that survives both does not depend "
        "on which tray the model trained on. Under this dataset's one-bundle-per-class-per-fold "
        "structure that is the closest available approximation to acquisition generalisation.\n",
        "**Rank efficiency** is the participation-ratio effective rank of the selection's "
        "correlation matrix, divided by k. 1.0 means mutually orthogonal bands; 0.15 at k = 40 "
        "means the set is worth about six independent directions wearing forty names.\n",
    ]
    return lines


def _flags_section(flags: list[dict[str, Any]]) -> list[str]:
    if not flags:
        return ["## 6. Automated checks\n", "*No flags raised.*\n"]
    lines = [
        "## 6. Automated checks — trends, instabilities and suspicious results\n",
        "Raised by `analysis.detect_flags`, ordered by how much each one changes the "
        "conclusion. Each check exists because the corresponding mistake is one this project's "
        "audit found, or one this study's design makes possible.\n",
    ]
    for flag in flags:
        mark = SEVERITY_MARK.get(flag["severity"], "•")
        lines.append(
            f"{mark} **{flag['severity'].upper()} · `{flag['code']}`** — {flag['message']}\n"
        )
    return lines


def _confirm_section(
    cfg: BandStudyConfig, confirm: pd.DataFrame, curves: pd.DataFrame
) -> list[str]:
    lines = ["## 7. Held-out confirmation\n"]
    if confirm.empty:
        return lines + [
            "*Not run.* The held-out split has not been touched. Run "
            "`python -m spectralquadnet.bandstudy.cli confirm` **after** reading §8 — the "
            "ordering is the point of having a separate stage.\n"
        ]
    rows = []
    for r in confirm.to_dict("records"):
        ci = r.get("ci")
        if isinstance(ci, str):
            try:
                ci = json.loads(ci.replace("'", '"'))
            except json.JSONDecodeError:
                ci = None
        interval = (
            f"[{ci['lo']:.4f}, {ci['hi']:.4f}]" if isinstance(ci, dict) and "lo" in ci else "—"
        )
        rows.append(
            [
                r.get("fold"),
                r.get("method"),
                r.get("budget"),
                r.get("proxy"),
                _fmt(r.get("macro_f1")),
                interval,
                _fmt(r.get("balanced_accuracy")),
                r.get("why", ""),
            ]
        )
    lines += [
        "Scored **once**, on `val ∪ test`, after the recommendation in §8 was fixed. The "
        "configurations were chosen on calib; nothing here fed back into that choice.\n",
        markdown_table(
            ["fold", "method", "k", "proxy", "macro-F1", "95% CI", "balanced acc", "why this row"],
            rows,
        ),
        "\n*Every interval is a percentile bootstrap over patches. It is sampling noise on a "
        "fixed split — not a confidence interval on the protocol. With two acquisition bundles "
        "per class, no amount of resampling patches within a held-out bundle speaks to how this "
        "would transfer to a third.*\n",
    ]
    lines += _calib_optimism(confirm, curves)
    return lines


def _calib_optimism(confirm: pd.DataFrame, curves: pd.DataFrame) -> list[str]:
    """How much higher calib scored than the held-out split, per configuration.

    The number that closes the loop on the protocol caveat in §1. Calib is a
    patch-level carve-out of the *same acquisition bundle* the model trained on,
    so it is expected to read high; what matters is whether the gap is roughly
    constant across configurations. A constant offset leaves every comparison
    the study made intact — it cancels. A gap that varies with the band budget
    would mean the budget curve measured on calib is a different curve from the
    one on held-out data, and the recommendation would have to be revisited.

    Computed here rather than in `analysis` on purpose: this is the one place a
    held-out number is allowed to be read, and it is read after the fact.
    """
    if confirm.empty or curves.empty:
        return []
    merged = confirm.merge(
        curves[["fold", "method", "proxy", "budget", "score"]].rename(
            columns={"score": "calib_score"}
        ),
        on=["fold", "method", "proxy", "budget"],
        how="inner",
    )
    if merged.empty:
        return []
    merged["gap"] = merged["calib_score"] - merged[METRIC]

    by_budget = merged.groupby("budget")["gap"].mean()
    spread = float(by_budget.max() - by_budget.min()) if len(by_budget) > 1 else 0.0
    verdict = (
        "roughly constant across budgets, so it cancels out of every comparison this study made"
        if spread < 0.05
        else "**not** constant across budgets, so the calib budget curve is not simply a shifted "
        "copy of the held-out one and the recommendation should be re-read against §7"
    )
    return [
        "\n### How optimistic was calib?\n",
        f"Mean `calib − heldout` macro-F1 over the {len(merged)} confirmed configurations: "
        f"**{merged['gap'].mean():+.4f}** (range {merged['gap'].min():+.4f} to "
        f"{merged['gap'].max():+.4f}).\n",
        markdown_table(
            ["k", "mean calib − heldout", "n"],
            [
                [int(k), f"{float(by_budget[k]):+.4f}", int((merged["budget"] == k).sum())]
                for k in sorted(by_budget.index)
            ],
        ),
        f"\nThe gap is {verdict}. It is expected to be positive: calib is a patch-level "
        "carve-out of the acquisition bundle the model trained on, whereas the held-out split is "
        "a different tray entirely — which is the leakage gap this repository exists to measure, "
        "appearing inside the band study's own protocol.\n",
    ]


def _neural_section(cfg: BandStudyConfig, neural: pd.DataFrame) -> list[str]:
    lines = ["## 8. Neural confirmation\n"]
    plan_path = cfg.neural_dir / "plan.json"
    if neural.empty:
        planned = ""
        if plan_path.exists():
            payload = json.loads(plan_path.read_text())
            planned = (
                f" {len(payload.get('runs', []))} runs across {len(payload.get('arms', []))} arms "
                f"are planned in `{plan_path}`; the commands are in "
                f"`{cfg.neural_dir/'commands.sh'}`."
            )
        return lines + [
            "*Not yet measured.*" + planned + "\n\n"
            "**This is the stage that tests the study's one untransferable claim.** Everything "
            "in §2 is measured on mean spectra, which discard all spatial structure; the "
            "project's own bracket puts ~25 macro-F1 points of the deployed model in exactly "
            "what they discard. CHANGES F-3 predicts the network's curve keeps rising past the "
            "proxies' plateau, so **the recommended budget in §9 is a lower bound until these "
            "runs report**.\n"
        ]

    grouped = (
        neural.groupby(["arm", "method", "budget"])
        .agg(
            mean_f1=("macro_f1", "mean"),
            min_f1=("macro_f1", "min"),
            max_f1=("macro_f1", "max"),
            n=("macro_f1", "size"),
        )
        .reset_index()
        .sort_values("budget")
    )
    lines += [
        "Runs of the repository's default composition, differing **only** in the band subset "
        "(`data.band_indices_path`) and the band count it implies. Mean ± range over folds × "
        "seeds, never a maximum.\n",
        markdown_table(
            ["arm", "method", "k", "runs", "macro-F1 mean", "min", "max", "range"],
            [
                [
                    r["arm"],
                    r["method"],
                    r["budget"],
                    r["n"],
                    _fmt(r["mean_f1"]),
                    _fmt(r["min_f1"]),
                    _fmt(r["max_f1"]),
                    _fmt(r["max_f1"] - r["min_f1"]),
                ]
                for r in grouped.to_dict("records")
            ],
        ),
        "\n*Interpret every delta against the run-to-run σ that ablation A12 measures. A delta "
        "smaller than σ is not evidence — and in the audited run, every reported delta was.*\n",
    ]
    return lines


def _conclusions(
    cfg: BandStudyConfig,
    recommendation: dict[str, Any],
    flags: list[dict[str, Any]],
    curves: pd.DataFrame,
    ranking: pd.DataFrame,
    neural: pd.DataFrame,
) -> list[str]:
    lines = ["## 9. Conclusions and recommendations for the neural experiments\n"]

    critical = [f for f in flags if f["severity"] == "critical"]
    if critical:
        lines += [
            "### Read these first — they qualify everything below\n",
            *[f"🔴 **{f['code']}** — {f['message']}\n" for f in critical],
        ]

    status = recommendation.get("status")
    budget = recommendation.get("recommended_budget")
    aggressive = recommendation.get("aggressive_budget")
    method = recommendation.get("recommended_method")
    full = recommendation.get("full_budget")

    lines += ["### The recommendation\n"]
    if status == "no_plateau":
        lines += [
            f"**Use all {full} bands.** No curve plateaued inside the evaluated range: every one "
            "was still within tolerance of its peak only at the largest budget. The study has "
            "established a **lower bound** on the useful band count, not a sufficient budget, and "
            "any reduction claimed from these results would be the same unfalsifiable elbow "
            "CHANGES M-14 found in the shipped 40- and 100-band selections.\n",
        ]
    else:
        lines += [
            markdown_table(
                ["", "budget", "method", "why"],
                [
                    [
                        "**Preferred**",
                        budget,
                        f"`{method}`",
                        "the largest budget any proxy family needs — buying the agreement of all "
                        "three costs bands and is the right default when the next experiment is "
                        "expensive",
                    ],
                    [
                        "Aggressive",
                        aggressive,
                        f"`{method}`",
                        "the smallest budget any proxy plateaus at; the gap between the two rows IS "
                        "the study's uncertainty about the answer",
                    ],
                    [
                        "Reference",
                        full,
                        "any",
                        "the full cube — every reduction is a reduction from this and it must stay "
                        "in the comparison",
                    ],
                ],
            ),
            f"\nMethod rationale: {recommendation.get('recommended_method_rationale')}.\n",
        ]
        if recommendation.get("fallback_reason"):
            lines.append(
                f"⚠️ Fallback path taken: `{recommendation['fallback_reason']}` — the preferred "
                "method is not the one that would have been chosen had every pre-registered "
                "criterion been met.\n"
            )
        runners = recommendation.get("runner_up_methods") or []
        if runners:
            lines.append(
                f"Runner-up methods worth an arm each: {', '.join(f'`{m}`' for m in runners)}.\n"
            )

    plateau = recommendation.get("plateau_by_proxy", {})
    if plateau:
        lines.append(
            "Per-proxy plateaus: "
            + ", ".join(f"`{p}` → k = {k}" for p, k in sorted(plateau.items()))
            + ". Where these disagree, the budget is a property of the estimator.\n"
        )

    # ── Trade-off ────────────────────────────────────────────────────
    if not curves.empty and isinstance(budget, int) and isinstance(full, int) and full > 0:
        best_at = curves[curves["budget"] == budget]["score"].max()
        best_full = curves[curves["budget"] == full]["score"].max()
        if np.isfinite(best_at) and np.isfinite(best_full):
            lines += [
                "### Performance / compute trade-off\n",
                f"At k = {budget} the best proxy reaches **{best_at:.4f}** against "
                f"**{best_full:.4f}** at k = {full}: a change of **{best_at - best_full:+.4f}** "
                f"macro-F1 for a **{100 * (1 - budget / full):.0f}%** reduction in input bands.\n",
                "A neural run's input-stage cost is roughly linear in the band count — the 3-D "
                "stem, the spectral tokeniser and the per-band index bank all scale with it — so "
                "that reduction is close to a proportional saving on the spectral pathway, and "
                "roughly nothing on the spatial one. It also reduces the per-patch read off the "
                "mmapped cube by the same fraction, which on this dataset is usually the binding "
                "constraint rather than the FLOPs.\n",
            ]

    # ── Uncertainty and limitations ──────────────────────────────────
    sigma = recommendation.get("decision_inputs", {}).get("sigma_pooled")
    lines += [
        "### Uncertainty\n",
        f"- Pooled replicate σ across the study: **{_fmt(sigma)}** macro-F1. Any difference "
        "between two budgets or two methods smaller than 2σ has not been shown to be a "
        "difference.",
        f"- Decisions were made on **calib** ({cfg.split_scheme}, folds {list(cfg.folds)}), never "
        "on the reported split.",
        f"- Every budget curve is a mean over {len(cfg.folds)} acquisition folds. Two is the "
        "maximum this dataset supports — there is no third bundle — so fold-to-fold spread is "
        "an n = 2 estimate and is reported as a range, never as a standard error.\n",
        "### Limitations\n",
        "1. **The proxies are not the model.** Every number in §2–§6 comes from classical "
        "estimators on mean spectra. That representation discards all spatial structure, and the "
        "project's bracket puts ~25 macro-F1 points of the deployed model in what it discards "
        "(CHANGES §19.4). A proxy plateau is a **lower** bound on the network's budget "
        "(CHANGES F-3).",
        "2. **One training bundle per class per fold.** Under the grouped protocol a class's "
        "training patches all come from a single tray, so there is zero within-class acquisition "
        "variance in training. A band that is stable across the two folds is the strongest "
        "evidence available here, and it is still evidence from two acquisitions.",
        "3. **Selection frequency is not importance.** Bands correlated above 0.99 are "
        "interchangeable; a band chosen often may be the arbitrary representative of a group "
        "rather than uniquely informative. The rank-efficiency column in §5 is the check.",
        "4. **The budget grid is finite.** A plateau is located to the nearest grid point, so "
        "the resolution near the recommendation is the local grid spacing, not 1 band.\n",
    ]

    # ── Next experiments ─────────────────────────────────────────────
    lines += ["### Recommended next experiments\n"]
    if neural.empty:
        lines += [
            "1. **Run the neural confirmation** — `python -m spectralquadnet.bandstudy.cli neural "
            "--execute`. Until it reports, the budget above is a proxy result. It is the only "
            "experiment here that can falsify the study's central number.",
        ]
    else:
        lines += [
            "1. **Extend the neural confirmation** to the budgets where the proxy and neural "
            "curves disagree — those are the informative ones, and they are now identifiable "
            "from §8.",
        ]
    lines += [
        "2. **Run A12 first if it has not reported.** Every delta in §8 is interpreted against "
        "run-to-run σ, and until σ is known no neural delta between two budgets means anything.",
        "3. **Re-run A2 with these band files.** A2 asks whether band selection outside the fold "
        "leaks materially; it currently compares a whole-corpus 40-band cube against a per-fold "
        "one. The `bands/` directory here supplies matched within-fold selections at every "
        "budget, which turns A2 from a two-point comparison into a curve.",
        "4. **Report the budget curve beside the leakage gap.** If the network's curve saturates "
        "much earlier under `stratified` than under `grouped`, the extra bands are carrying "
        "acquisition signal rather than variety signal — a direct, cheap test of this "
        "repository's headline question, using machinery that now exists.",
        "5. **Do not re-select bands on the reported split.** The `bands/` artifacts are "
        "per-fold and named `<method>_f<fold>_k<budget>.npy`; a run that loads another fold's "
        "file reintroduces exactly the leak this study was built to avoid.\n",
    ]
    return lines


def _evidence(cfg: BandStudyConfig, figure_paths: list[Path]) -> list[str]:
    lines = [
        "## 10. Where the evidence lives\n",
        markdown_table(
            ["artifact", "what it holds"],
            [
                [
                    f"`{cfg.analysis_dir}/curves.csv`",
                    "every (fold, method, proxy, budget) score with its spread",
                ],
                [f"`{cfg.analysis_dir}/trends.csv`", "the per-curve shape verdict and plateau"],
                [
                    f"`{cfg.analysis_dir}/null_margins.csv`",
                    "each method's advantage over a random subset",
                ],
                [
                    f"`{cfg.analysis_dir}/stability.csv`",
                    "replicate agreement per (fold, method, budget)",
                ],
                [
                    f"`{cfg.analysis_dir}/cross_fold_agreement.csv`",
                    "do the two acquisition folds choose the same bands",
                ],
                [
                    f"`{cfg.analysis_dir}/redundancy.csv`",
                    "correlation, effective rank and coverage per set",
                ],
                [f"`{cfg.analysis_dir}/method_ranking.csv`", "the method comparison"],
                [
                    f"`{cfg.analysis_dir}/wavelength_frequency.csv`",
                    "selection frequency per band, in nm",
                ],
                [f"`{cfg.analysis_dir}/flags.json`", "every automated check that fired"],
                [
                    f"`{cfg.analysis_dir}/recommendation.json`",
                    "the machine-readable recommendation",
                ],
                [
                    f"`{cfg.selections_dir}/`",
                    "every selection: ranking, per-budget sets, timings, failures",
                ],
                [
                    f"`{cfg.bands_dir}/`",
                    "band index arrays + λ CSVs, ready for `data.band_indices_path`",
                ],
                [f"`{cfg.proxy_dir}/records.jsonl`", "one row per proxy fit — the raw evidence"],
                [f"`{cfg.confirm_dir}/records.jsonl`", "the held-out confirmations"],
                [f"`{cfg.logs_dir}/`", "per-stage logs, including every held-out reveal"],
                [f"`{cfg.root}/{MANIFEST}`", "the study's configuration and stage outcomes"],
            ],
        ),
    ]
    if figure_paths:
        lines += [
            "\n### Figures\n",
            *[f"- `{p}`" for p in sorted(figure_paths)],
            "\n",
        ]
    return lines


# ══════════════════════════════════════════════════════════════════════
#  Driver
# ══════════════════════════════════════════════════════════════════════


def build_report(cfg: BandStudyConfig, render_figures: bool = True) -> Path:
    """Assemble ``REPORT.md`` from the analysis artifacts.

    Raises:
        FileNotFoundError: The analysis stage has not run.
    """
    recommendation = bsanalysis.load_recommendation(cfg)
    flags = bsanalysis.load_flags(cfg)
    curves = _read(cfg, "curves")
    trends = _read(cfg, "trends")
    margins = _read(cfg, "null_margins")
    ranking = _read(cfg, "method_ranking")
    stability = _read(cfg, "stability")
    cross_fold = _read(cfg, "cross_fold_agreement")
    redundancy = _read(cfg, "redundancy")
    consensus = _read(cfg, "wavelength_frequency")
    confirm = bsanalysis.confirm_table(cfg)
    neural = bsneural.collect_neural(cfg)

    manifest_path = cfg.root / MANIFEST
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    splits_path = cfg.cache_dir / "splits.json"
    splits = json.loads(splits_path.read_text()) if splits_path.exists() else {}

    inputs = load_inputs(cfg, quiet=True)
    figure_paths: list[Path] = []
    if render_figures:
        mean_spectrum = np.asarray(inputs.spectra, dtype=np.float64).mean(axis=0)
        figure_paths = bsfigures.render_all(cfg, mean_spectrum=mean_spectrum)

    sections: list[str] = []
    sections += _header(cfg, manifest)
    sections += _protocol(cfg, splits)
    sections += _budget_section(cfg, curves, trends)
    sections += _method_section(cfg, ranking, margins)
    sections += _wavelength_section(
        cfg, consensus, inputs, int(recommendation.get("recommended_budget", 0))
    )
    sections += _stability_section(cfg, stability, cross_fold, redundancy)
    sections += _flags_section(flags)
    sections += _confirm_section(cfg, confirm, curves)
    sections += _neural_section(cfg, neural)
    sections += _conclusions(cfg, recommendation, flags, curves, ranking, neural)
    sections += _evidence(cfg, figure_paths)

    cfg.report_path.parent.mkdir(parents=True, exist_ok=True)
    cfg.report_path.write_text("\n".join(sections) + "\n")
    _log.info("report → %s", cfg.report_path)
    return cfg.report_path
